name: test-h5

on:
  push:
    branches:
      - "test/h5"

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: use node (16)
        uses: actions/setup-node@v1
        with:
          node_version: 16

      - name: use npm (8)
        run: npm install -g npm

      - name: install
        run: npm install --force

      - name: npm bulid h5
        run: nx run h5:build

