app: samuraisApp
stage: ${env:STAGE}

component: nest
name: samurais

inputs:
  src:
    src: ./
    exclude:
      - .env

  region: ap-guangzhou
  runtime: Nodejs16.12.0
  functionName: ${name}-${stage}-${app}
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
